### ISSUE TITLE
can't run by 'quasar dev -m electron'

### ISSUE THREAD

**Issue by guozanhua** [open-source-labs/OverVue#100]
![image](https://user-images.githubusercontent.com/157069/105812813-d1fd7700-5fe9-11eb-8e59-4779a2312709.png)

**Comment by guozanhua** [comment]
• Compiling:
 ├── Renderer process █████████            40% building 83/87 modules 4 active
 └── Main process     █                    0%

(node:2824) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)

 • Compiling:
 ├── Renderer process ████████████████████ 100% done in 10537 ms
 └── Main process     █                    0%



 ERROR  Failed to compile with 457 errors                                                                    下午3:23:15

These dependencies were not found:

* core-js/modules/es6.array.find-index.js in ./node_modules/quasar/src/components/menu/ClickOutside.js, ./node_modules/quasar/src/components/select/QSelect.js and 3 others
* core-js/modules/es6.array.find.js in ./node_modules/quasar/src/components/editor/editor-utils.js, ./node_modules/quasar/src/components/select/QSelect.js and 2 others
* core-js/modules/es6.array.from.js in ./node_modules/quasar/src/mixins/file.js
* core-js/modules/es6.array.iterator.js in ./node_modules/quasar/src/ssr-update.js, ./node_modules/quasar/src/icon-set.js and 51 others
* core-js/modules/es6.function.name.js in ./node_modules/quasar/src/install.js, ./node_modules/quasar/src/components/icon/QIcon.js and 11 others
* core-js/modules/es6.map.js in ./node_modules/quasar/src/utils/is.js
* core-js/modules/es6.number.constructor.js in ./node_modules/quasar/src/components/btn/QBtn.js, ./node_modules/quasar/src/components/chip/QChip.js and 23 others
* core-js/modules/es6.object.assign.js in ./node_modules/quasar/src/ssr-update.js, ./node_modules/quasar/src/history.js and 10 others
* core-js/modules/es6.object.freeze.js in ./node_modules/quasar/src/install.js
* core-js/modules/es6.object.keys.js in ./node_modules/quasar/src/ssr-update.js, ./node_modules/quasar/src/icon-set.js and 50 others

**Comment by MrBeeAreWhy** [comment]
Closing issue for now -- over 12 months old and OverVue has had multiple iterations since then. Please try again with OverVue 6.0 as it has fully updated dependencies and is less likely to run into issues as long as you are running the most recent stable release of Node.
