### ISSUE TITLE
App · ⚠️  Command name was not available. Please run again.

### ISSUE THREAD

**Issue by unzoa** [open-source-labs/OverVue#124]
OverVue git:(master) quasar dev -m electron

 Dev mode.......... electron
 Pkg quasar........ v1.0.3
 Pkg @quasar/app... v1.9.6
 Debugging......... enabled

 App · Running "@quasar/testing" Quasar App Extension...
 App · Running "@quasar/testing-unit-jest" Quasar App Extension...
 App · Reading quasar.conf.js
 App · Checking listening address availability (0.0.0.0:8080)...
 App · Generating legacy js code (ES5); use "--modern" param for ES6+
 App · Extending Renderer process Webpack config
 App · Extending Main process Webpack config
 App · Generating Webpack entry point
 App · Booting up...

 • Compiling:
 ├── Renderer process ████████████████████ 100% done in 16830 ms
 └── Main process     █                    0% 

 DONE  Compiled successfully in 16837ms                       11:57:54 ├F10: AM┤

ℹ ｢wds｣: Project is running at http://0.0.0.0:8080/
ℹ ｢wds｣: webpack output is served from 
ℹ ｢wds｣: 404s will fallback to /index.html
 App · Building main Electron process...

 • Compiling:
 ├── Renderer process ████████████████████ 100% done in 16830 ms
 └── Main process     ████████████████████ 100% done in 521 ms

 App · Webpack built Electron main process

Hash: 581c266cd5a882569e45
Version: webpack 4.43.0
Time: 522ms
Built at: 2021-12-17 11:57:55 ├F10: AM┤
           Asset     Size         Chunks             Chunk Names
electron-main.js  118 KiB  electron-main  [emitted]  electron-main
Entrypoint electron-main = electron-main.js

 App · Booting up Electron process...
 App · ⚠️  Command name was not available. Please run again.

**Comment by unzoa** [comment]
Duplicate of #

**Comment by thomas-topway-it** [comment]
@unzoa what was the solution for this issue ?

**Comment by thomas-topway-it** [comment]
I can now answer: delete node_modules and `npm i` again

**Comment by kamasuPaul** [comment]
> I can now answer: delete node_modules and `npm i` again

Thank you. This resolved my issue
