### ISSUE TITLE
 Some problems encountered when running

### ISSUE THREAD

**Issue by zlf4865231** [open-source-labs/OverVue#76]
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object 

 Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

Can you tell me what problems  happened?

**Comment by liangxuev** [comment]
I have the same problem.

**Comment by xiaoshitou123** [comment]
+1

**Comment by MrDuCongcong** [comment]
I have the same problem

**Comment by zhenghaizhang** [comment]
I have the other problem.   windows system.

(node:18252) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside
of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)(node:18252) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by dnohashi** [comment]
Is the error occurring when running in development? Windows users may be facing complications when running this application, for whatever reason. We're looking into it.
