### ISSUE TITLE
mockup is uploaded but screen is getting black

### ISSUE THREAD

**Issue by rotemoz84** [open-source-labs/OverVue#78]
I am trying to use a mock-up for designing my app, but after uploading my screenshot, the working space becomes black (instead of the gray grid), and nothing happens.
I can add components, keep working normally, but without seeing the picture I just uploaded.
I do see it in the dashboard on the left

**Comment by dnohashi** [comment]
Hi, rotemoz84. What's the file format of the mock-up? We can try to re-create the problem.

**Comment by rotemoz84** [comment]
Thanks for reaching out :)
I have tried several options:
1. jpg - size of 128kb
2. png - size of 25.8kb
3. jpg - size of 1.73mb

**Comment by dnohashi** [comment]
What OS are you running this on? We're having issues with file paths with Windows and haven't yet released a working version of it.

**Comment by rotemoz84** [comment]
oh well...than that's the problem :) 
I'm working with Windows
Any plans for this release?
I'll keep watching

**Comment by mitse** [comment]
Hi, do you plan for any release that fixes file path problem?
Thank you in advance.

**Comment by JojuOlaode** [comment]
The file path issue for Windows has been resolved. Please let us know if you are experiencing any additional issues uploading mockups.
