### ISSUE TITLE
make simple step by step tutorial using overvue please

### ISSUE THREAD

**Issue by azulkipli** [open-source-labs/OverVue#79]
make simple step by step video tutorial how to use overvue would be great

**Comment by JojuOlaode** [comment]
[Here](https://medium.com/better-programming/open-source-a-walkthrough-of-overvue-v2-8e46c5682eb9) is an article that walks through creating a project using OverVue. Let us know if you have specific questions about a certain feature.

**Comment by giridhart** [comment]
A video tutorial would be great. Looked on YouTube but couldn't find any. I wanted to clone some website ui but can't really figure out where to start.

**Comment by MrBeeAreWhy** [comment]
OverVue 6 includes a getting started tutorial and explains how to use the application -- in addition it has streamlined the UI so that the application as a whole is easier to use. Please reach out again if you have any issues with our newest version!
