### ISSUE TITLE
import from existing vue project

### ISSUE THREAD

**Issue by wangzhen-fit2cloud** [open-source-labs/OverVue#83]
Hi there, thanks for your great job.
Would you consider the feature about importing existing vue project into this tool?

**Comment by JojuOlaode** [comment]
That is a great suggestion! We haven’t considered it yet, but we are open to having contributors work on new features as well.

**Comment by jbbake** [comment]
Hi @wangzhen-fit2cloud -- importing an existing Vue component, as well as a project JSON, is now available with OverVue 6.0!

**Comment by wangzhen-fit2cloud** [comment]
> Hi @wangzhen-fit2cloud -- importing an existing Vue component, as well as a project JSON, is now available with OverVue 6.0!

Thanks for your reply and your work for this feature. I'll try this new version later.
